name: Compile

on:
  release:
    types: [published]

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    name: Build on ${{ matrix.os }} with ${{ matrix.compiler }}.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: Linux

          - os: macos-latest
            target: Macos

          - os: windows-latest
            target: Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python v3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Build binaries for cqlsh and keys_generator
        run: |
          pip3 install -r requirements.txt

          mkdir dist
          pyinstaller --noconfirm --clean --noupx --distpath dist/cqlsh-407-$(uname -s)-$(uname -m) --onefile v6.0.0-ACv4.0.7/cqlsh.py -n cqlsh-407
          pyinstaller --noconfirm --clean --noupx --distpath dist/cqlsh-410-$(uname -s)-$(uname -m) --onefile v6.1.0-ACv4.1.0/cqlsh.py -n cqlsh-410
          pyinstaller --noconfirm --clean --noupx --distpath dist/keys_generator-$(uname -s)-$(uname -m) --onefile keys_generator/keys_generator.py

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}